export { Agent, type AgentEvent, type AgentOptions, type QueueMode } from "./agent.ts";
export {
	BRANCH_SUMMARY_PREAMBLE,
	type BranchPreparation,
	type BranchSummaryDetails,
	type BranchSummaryResult,
	type CollectEntriesResult,
	collectEntriesForBranchSummary,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	prepareBranchEntries,
} from "./branch.ts";
export type { FileInfo, FileKind, FileSystem, Shell, ShellExecResult } from "./capabilities.ts";
export { createCodingTools } from "./coding-tools.ts";
export {
	type CompactionPreparation,
	type CompactionResult,
	type CompactionSettings,
	type ContextUsageEstimate,
	type CutPointResult,
	calculateContextTokens,
	computeFileLists,
	DEFAULT_COMPACTION_SETTINGS,
	estimateContextTokens,
	estimateTokens,
	extractFileOpsFromMessage,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	formatFileOperations,
	generateSummary,
	prepareCompaction,
	runCompaction,
	SUMMARIZATION_SYSTEM_PROMPT,
	serializeConversation,
	shouldCompact,
} from "./compaction.ts";
export {
	FileError,
	type FileErrorCode,
	HttpError,
	SessionError,
	type SessionErrorCode,
	ShellError,
	type ShellErrorCode,
	TauError,
	type TauErrorCode,
	toError,
} from "./errors.ts";
export {
	type AgentEndEvent,
	type AgentRunResult,
	type AgentSpawnOptions,
	type AgentStartEvent,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type CompactionReason,
	type ContextEvent,
	type ContextEventResult,
	type CustomMessageInput,
	type Extension,
	type ExtensionAPI,
	type ExtensionCapabilities,
	type ExtensionContext,
	type ExtensionHandler,
	type ExtensionHostActions,
	type ExtensionPaths,
	ExtensionRegistry,
	type InputEvent,
	type InputEventResult,
	type MessageEndEvent,
	type MessageEndEventResult,
	type MessageStartEvent,
	type MessageUpdateEvent,
	type ModelSelectEvent,
	type ModelSelectEventResult,
	type ProjectTrustEvent,
	type ProjectTrustEventResult,
	type RegisteredCommand,
	type RegisteredCommandResult,
	type RegisteredFlag,
	type RegisteredShortcut,
	type ResourcesDiscoverEvent,
	type ResourcesDiscoverResult,
	type SessionBeforeCompactEvent,
	type SessionBeforeCompactResult,
	type SessionBeforeForkEvent,
	type SessionBeforeForkResult,
	type SessionBeforeTreeEvent,
	type SessionBeforeTreeResult,
	type SessionCompactEvent,
	type SessionInfoChangedEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ThinkingLevel,
	type ThinkingLevelSelectEvent,
	type ThinkingLevelSelectEventResult,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolExecutionEndEvent,
	type ToolExecutionStartEvent,
	type ToolExecutionUpdateEvent,
	type ToolResultEvent,
	type ToolResultEventResult,
	type TreePreparation,
	type TurnEndEvent,
	type TurnStartEvent,
	type UiCapability,
	type UserBashEvent,
	type UserBashEventResult,
} from "./extensions.ts";
export {
	type AgentMessage,
	type AssistantMessage,
	type BranchSummaryMessage,
	type CompactionSummaryMessage,
	type CustomMessage,
	emptyUsage,
	type ImageContent,
	messageText,
	type StopReason,
	type TextContent,
	type ThinkingContent,
	type ToolCall,
	type ToolResultMessage,
	thinkingText,
	toolCallsOf,
	type Usage,
	type UsageCost,
	type UserMessage,
} from "./messages.ts";
export {
	type ChatStreamEvent,
	type JsonSchema,
	OPENAI_COMPLETIONS_API,
	type OpenAICompatConfig,
	streamChatCompletion,
	type ToolDefinition,
} from "./openai.ts";
export {
	defaultPlatform,
	type Platform,
	type PlatformBodyReader,
	type PlatformFetch,
	type PlatformRequestInit,
	type PlatformResponse,
	type TauAbortSignal,
	type Utf8Decoder,
} from "./platform.ts";
export {
	type ForkOptions,
	getEntriesToFork,
	InMemorySessionRepo,
	InMemorySessionStore,
	JsonlSessionRepo,
	messagesFromPath,
	type RestoredSession,
	restoreSession,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionMetadata,
	SessionRecorder,
	type SessionRepo,
	type SessionStore,
	sessionDirSlug,
} from "./session.ts";
export { type SseEvent, SseParser } from "./sse.ts";
export { errorResult, optionalNumber, requireString, type Tool, type ToolResult } from "./tools.ts";
export { uuidv7 } from "./uuid.ts";
